import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <nav>
            <Link href="/">Dashboard</Link>
            <Link href="/costs">Costs</Link>
            <Link href="/summary">Summary</Link>
            <Link href="/connect">Import</Link>
            <Link href="/export">Export</Link>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
